version: "3"

services:
  postgresql:
    container_name: unimed-postgres
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=unimed-liu-db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    volumes:
      - ./data:/bitnami/postgresql